/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 asana.gltf
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'
import { Flex, Box } from "@react-three/flex";

export default function Model(props) {
  const { nodes, materials } = useGLTF('/EllieWebsiteRedo/asana.gltf')
  return (
    <Box width="auto" height="auto" flexGrow={0.5} centerAnchor>

      <group {...props} dispose={null}>
        <group position={[0, 0, -0.01]} rotation={[-Math.PI / 2, 0, 0]}>
          <group scale={0.1}>
            <group position={[-0.29, 0, 0.26]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.Body1.geometry} material={materials.Plastic} scale={400} />
            </group>
            <group position={[-0.29, 0, 0.26]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.Body1_2.geometry} material={materials.Plastic} scale={400} />
            </group>
            <group position={[-0.29, 0, 0.26]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.Body1_3.geometry} material={materials.Plastic} scale={400} />
            </group>
            <group position={[-0.29, 0, 0.26]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.Body1_4.geometry} material={materials['Plastic 2']} scale={400} />
            </group>
          </group>
        </group>
        <PerspectiveCamera makeDefault={false} far={2} near={0} fov={31} position={[-0.09, -0.02, -0.24]} rotation={[2.99, -0.31, 3.09]} />
      </group>
    </Box>
  )
}

useGLTF.preload('/asana.gltf')
