/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 bd.gltf
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/EllieWebsiteRedo/bd.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.01, 0, 0]}>
        <group position={[-0.01, 0.01, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.25, 1.25, 0.95]}>
          <group scale={0.5}>
            <mesh geometry={nodes.Body1_3.geometry} material={materials['Matte 3']} scale={50} />
            <mesh geometry={nodes.Body1_4.geometry} material={materials['Brushed Aluminum']} scale={50} />
          </group>
        </group>
        <group position={[-0.24, -0.02, -0.16]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <group scale={0.5}>
            <group position={[-2.54, -0.16, -3.36]}>
              <mesh geometry={nodes.Body1.geometry} material={materials.Matte} scale={50} />
            </group>
            <group position={[-2.54, -0.16, -3.36]}>
              <mesh geometry={nodes.Body1_2.geometry} material={materials['Glass 2']} position={[-0.63, -1.19, 0]} rotation={[0, 0, 0.65]} scale={[42.95, 38.9, 50]} />
              <mesh geometry={nodes.Body2.geometry} material={materials['Glass 2']} position={[1.11, -0.31, 0]} rotation={[0, 0, -0.44]} scale={[36.5, 37.4, 50]} />
            </group>
          </group>
        </group>
      </group>
      <PerspectiveCamera makeDefault={false} far={2} near={0} fov={34.52} position={[0.51, 0.3, 0.5]} rotation={[-0.36, 0.75, 0.25]} />
    </group>
  )
}

useGLTF.preload('/bd.gltf')
