/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 gfd.gltf
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/EllieWebsiteRedo/gfd.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.07, 0.01, -0.01]} rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0.1}>
          <group position={[0, 0.85, 1.2]} rotation={[-Math.PI, 0, 0]}>
            <mesh geometry={nodes.Body1.geometry} material={materials['Concrete_Brushed_01 2']} scale={200} />
            <mesh geometry={nodes.Body14.geometry} material={materials['Concrete_Brushed_01 2']} scale={200} />
          </group>
          <mesh geometry={nodes.Body1_2.geometry} material={materials['Glossy Paper']} scale={200} />
        </group>
      </group>
      <PerspectiveCamera makeDefault={false} far={2} near={0} fov={34.52} position={[0.43, 0.3, 0.57]} rotation={[-0.36, 0.75, 0.25]} />
    </group>
  )
}

useGLTF.preload('/gfd.gltf')
