/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 logo.gltf
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/EllieWebsiteRedo/logo.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-3.445, -0.265, 0.655]} rotation={[0, 0, 0.01]} scale={[45.485, 45.485, 83.765]}>
        <mesh geometry={nodes.svgMesh1.geometry} material={materials.Gelatin} position={[0.005, 0, -0.005]} scale={[0.45, 0.45, 0.18]} />
      </group>
      <group position={[1, 0.08, 0.52]} rotation={[0, 0, 0.045]} scale={[24.7, 24.7, 45.485]}>
        <mesh geometry={nodes.svgMesh1_2.geometry} material={materials.Gelatin} position={[-0.005, -0.005, -0.005]} scale={[0.56, 0.56, 0.28]} />
      </group>
      <PerspectiveCamera makeDefault={false} far={8.215} near={0} fov={34.52} position={[0.25, 1.75, 0.25]} rotation={[-0.36, 0.75, 0.25]} />
    </group>
  )
}

useGLTF.preload('/logo.gltf')
